# Generated by Django 3.2.5 on 2021-07-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('prerequisites', models.TextField()),
                ('corequisites', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
