# Generated by Django 3.2.5 on 2021-07-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210711_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
