# Generated by Django 3.2.5 on 2021-07-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210712_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
